# Generated by Django 5.1.15 on 2026-06-24 18:47

import django.db.models.deletion
import emr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("section_a", models.JSONField(default=emr.models.default_section_a)),
                ("section_b", models.JSONField(default=emr.models.default_section_b)),
                ("section_c", models.JSONField(default=emr.models.default_section_c)),
                ("section_d", models.JSONField(default=emr.models.default_section_d)),
                ("section_e", models.JSONField(default=emr.models.default_section_e)),
                ("section_f", models.JSONField(default=emr.models.default_section_f)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chief_complaint", models.CharField(blank=True, max_length=300)),
                ("chat_transcript", models.TextField(blank=True)),
                ("doctor_summary", models.TextField(blank=True)),
                ("intake_data", models.JSONField(blank=True, default=dict)),
                ("diagnosis", models.TextField(blank=True)),
                ("prescription", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="emr.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
