# Generated by Django 5.1.15 on 2026-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visit",
            name="prescription_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
